# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Warwick iGEM wiki theme"
license = "MIT"
licenselink = "https://raw.githubusercontent.com/Warwick-iGEM-2021/wiki-theme/main/LICENSE"
description = "Adaptation of the Elate theme ported to Hugo by Pieter Saey"
homepage = "https://github.com/Warwick-iGEM-2021/wiki-theme"
tags = ["Elate", "Hugo", "parallax"]
min_version = 0.17

[author]
  name = "Edmund Goodman"
  homepage = "https://edmundgoodman.github.io"

[original]
  name = "Pieter Saey"
  homepage = "http://saey55.gitlab.io/pietercv"
